CREATE TABLE account
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    user_id BIGINT,
    balance DOUBLE PRECISION,
    deposit DOUBLE PRECISION,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE email_data
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    user_id BIGINT,
    email   VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_email_data PRIMARY KEY (id)
);

CREATE TABLE phone_data
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5)  NOT NULL,
    user_id BIGINT,
    phone   VARCHAR(13) check ( length(phone) = 13 ) NOT NULL,
    CONSTRAINT pk_phone_data PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL,
    name          VARCHAR(500),
    date_of_birth date,
    password      VARCHAR(500) check ( length(password) >= 8),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE email_data
    ADD CONSTRAINT uc_email_data_email UNIQUE (email);

ALTER TABLE phone_data
    ADD CONSTRAINT uc_phone_data_phone UNIQUE (phone);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE email_data
    ADD CONSTRAINT FK_EMAIL_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE phone_data
    ADD CONSTRAINT FK_PHONE_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);