CREATE TABLE deposit
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status         BOOLEAN                                 NOT NULL,
    account_id    BIGINT,
    start_balance  DOUBLE PRECISION,
    amount         DOUBLE PRECISION,
    amount_stopped DOUBLE PRECISION,
    CONSTRAINT pk_deposit PRIMARY KEY (id)
);

ALTER TABLE users
    ADD account_id BIGINT;

ALTER TABLE account
    ADD CONSTRAINT uc_account_user UNIQUE (user_id);

ALTER TABLE deposit
    ADD CONSTRAINT FK_DEPOSIT_ON_ACCOUNT_IDO FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (id);

ALTER TABLE account
    DROP COLUMN deposit;

ALTER TABLE account
    ALTER COLUMN user_id SET NOT NULL;